### ISSUE TITLE
Setup trouble

### ISSUE THREAD

**Issue by tkoolen** [stack-of-tasks/pinocchio-benchmarks#6]
Hey guys. I wanted to try running this locally, but I'm having some trouble setting up the non-docker version.

First, I think you're missing a `git submodule update --init --recursive`. However, running that results in

```
error: Server does not allow request for unadvertised object 94c4d6d5c65b8f0a5f9963db7d93e9568f8aa3db
Fetched in submodule path 'benchmark', but it did not contain 94c4d6d5c65b8f0a5f9963db7d93e9568f8aa3db. Direct fetching of that commit failed.
```

Second, installing RBDL according to the instructions results in boost-related errors (even though I do have `libboost-dev` installed via `apt-get`):

```
/home/twan/code/pinocchio-benchmarks/libs/rbdl/addons/urdfreader/urdfreader.cc:15:9: error: ‘boost’ does not name a type; did you mean ‘bool’?
 typedef boost::shared_ptr<urdf::Link> LinkPtr;
```

I think this may just be a result of the submodule update failure.

Thanks!

**Comment by nim65s** [comment]
Hi,

I can't reproduce this issue. Which version of Ubuntu are you using ?
Could you try with the `./compile.sh` script ?

Maybe this is only an issue with the README…

**Comment by tkoolen** [comment]
Ubuntu 18.04. I'm just stuck at fetching all the submodules right now. You really can't reproduce this issue from a fresh clone of the repo?

**Comment by nim65s** [comment]
Well… That's interesting.

I ran the following script simultaneously on two dockers : 16.04 & 18.04:
```
set -ex
cd
apt update -qqy && apt install -qqy git ccache clang-6.0 cmake libcppunit-dev libboost-all-dev liburdfdom-dev
git clone --recursive https://github.com/stack-of-tasks/pinocchio-benchmarks.git
cd pinocchio-benchmarks/
git submodule update --init --recursive
```

It worked on 16.04, but I was able to reproduce your error on 18.04.

I will update the submodules.

**Comment by nim65s** [comment]
Amazing, it is now working on 18.04, but not on 16.04 anymore. I had no idea that git could be behaving like that.

**Comment by nim65s** [comment]
@tkoolen I think the setup has been fixed, as I can now run `git clone --recursive https://github.com/stack-of-tasks/pinocchio-benchmarks.git` and `./compile.sh` on both 16.04 & 18.04.

Can you check that, and close this issue if this is working for you ?

Now, we have another issue with RBDL, but this call for a separate ticket: #8

**Comment by tkoolen** [comment]
I can confirm that `git clone --recursive` now works on 18.04.

I'm still having trouble with RBDL though. The `find_package(BOOST)` call is commented out for some reason:

https://bitbucket.org/rbdl/rbdl/src/16820567f14484eda2863e2bf7bb734c9c21d74d/addons/urdfreader/CMakeLists.txt?at=default#lines-29

But uncommenting that didn't help. I was able to compile RBDL by adding `-DRBDL_USE_ROS_URDF_LIBRARY=OFF` to the CMake arguments.

**Comment by ferrolho** [comment]
I am having a similar issue. Both
```bash
git clone https://github.com/stack-of-tasks/pinocchio-benchmarks.git
cd pinocchio-benchmarks
git submodule update --init --recursive
```
and
```bash
git clone --recursive https://github.com/stack-of-tasks/pinocchio-benchmarks.git
```
result in:
```
error: Server does not allow request for unadvertised object eee8b05c97d7b832bf67d6e000958d012ab30165
Fetched in submodule path 'libs/benchmark', but it did not contain eee8b05c97d7b832bf67d6e000958d012ab30165. Direct fetching of that commit failed.
```
---

This seems to have helped a bit:
```bash
git submodule update --depth 100
```
...but some of the submodules under `libs/` remain empty.

Afterwards, when running `./run.sh` I also get:

```bash
Error while processing body 'rgbd_link': rotation of body frames not yet supported. Please rotate the joint frame instead.
Error constructing model from urdf file.
```

Nonetheless, I do get some of the output `*.txt` under `data/`.

P.s. - I believe `graphs.py` is also outdated.

@tkoolen, would you kindly share the results from your benchmarking? I'm mostly interested in the performance of Julia against RBDL and Pinocchio. Thanks!

**Comment by nim65s** [comment]
Sorry for the delay, we are releasing pinocchio v2.1.0, I will handle the troubles here just after that.
The issue with the git clone is about google benchmarks messing its history, it's not the first time. Don't worry about this one, just ignore it, as we found that running the benchmarks manually provide more accurate results.

**Comment by jcarpent** [comment]
@ferrolho You can also run the benchmarks in Pinocchio, without using this repo. I will try to put some info about that on the main repo of Pinocchio.

**Comment by ferrolho** [comment]
@jcarpent if you could add that info to the README.md of Pinocchio that would be awesome! Thank you very much.
